server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "2CNA6tIUosBKzREgym0LWBt9KbTFTbFuadSARDDyKo6i0RxrtDrj+s0dhaQ2b+7G"
