server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/identity_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "2CNA6tIUosBKzREgym0LWBt9KbTFTbFuadSARDDyKo6i0RxrtDrj+s0dhaQ2b+7G"
  valid-duration: 60 # in second, access token will be expired after 60s
  refreshable-duration: 120 # in seconds, refresh access token will be expired after 120s